Feature/evaluation updates
2501-ai/honest_benchmark pull request #1
Opened 2024-09-27 16:24 UTC by shide1989

## Today's menu 🧠🧟  : 
- Reworked all the code (Thank you ChatGPT) to make it cleaner and better.
- Added benchmark report class to manage all the test and result data
- Tested 30 AI Tests with OpenAI / Cerebras or Claude (depending on availability)
- Added tests summary to have a few insights on how the tests perform (will be improved later)

### Side dishes:
- Added the possibility to run a custom command to run a test
- Updated test format

2024-09-28 01:22 UTC, alxpereira requested changes

2024-09-28 01:22 UTC, alxpereira commented on benchmark_report.py
> +        self.model_pairs = self.config.get('model_pairs', [])
can we add `preprocessor` too ? 
for the moment it will be mostly llama70-cerebras I guess but just to have it into the report equation

2024-09-28 01:22 UTC, alxpereira commented on config/benchmark_config.json
> +    ["openai/gpt4o", "anthropic/claude3-opus"]
shall we display that in the repo ?

2024-09-28 01:22 UTC, alxpereira commented on config/benchmark_config.json
> +    ["openai/gpt4o", "anthropic/claude3-opus"]
maybe putting only an example, as an env. since the repo is open source

2024-09-28 01:22 UTC, alxpereira commented on config/honest_benchmark_old.jsonl
> +{"id":"honest_1", "input":"change the background to red using tailwind", "labels":"frontend,html,css", "test": "output = \"PASS\" if \"bg-red\" in open('./files/honest_1/index.html').read() or \"back
why keeping old ? we have git for that :)

2024-09-28 01:22 UTC, alxpereira commented on config/honest_benchmark.jsonl
> +{"id": "honest_33", "input": "create a hello.txt file with the content 'hello world'", "test_script": "output = \"PASS\" if open('./datasets/honest_33/hello.txt').read().strip() == 'hello world' else
globally, I think our questions should increase in complexity, should have more "edgy" cases
the idea of the benchmark is be realistic and both difficult, running 100% should be an exploit, I expect most MoM running like 70~80% accuracy. 

for example we can include a broken Dockerfile into the zip and ask the bot to run it, find the issue inside and fix it. etc...

2024-09-28 01:22 UTC, alxpereira commented on convert.py
> +    input_path = 'honest_benchmark_old.jsonl'
do we need that ?

2024-09-28 01:22 UTC, alxpereira commented on scripts/extract_json_unique_keys.py
> +import argparse
as this is related to test #21, should be into the folder of the test

2024-10-03 14:28 UTC, shide1989 commented on convert.py
> +    input_path = 'honest_benchmark_old.jsonl'
nope, will be removed

2024-10-03 14:29 UTC, shide1989 commented on scripts/extract_json_unique_keys.py
> +import argparse
I added the possibility to evaluate a test from a command, so i used the /scripts dir as the evaluation scripts dir.
wdyt ?

2024-10-03 14:38 UTC, shide1989 commented on config/benchmark_config.json
> +    ["openai/gpt4o", "anthropic/claude3-opus"]
you're right, I think we should find another way to make the pairs less identifiable like 'main-driver-1; 'secondary-1'; 'pre-processor-1'etc.. no ?

2024-10-04 01:07 UTC, alxpereira commented on config/benchmark_config.json
> +    ["openai/gpt4o", "anthropic/claude3-opus"]
codenames ?

2024-10-04 01:30 UTC, alxpereira commented on task_processor.py
> +    stdout, stderr, returncode = run_command(f"@2501 agents --flush")
- return variables not used, pls remove
- python Fstring not useful if no variable passed into it (perf)

2024-10-11 11:11 UTC, merged